# Site settings
title: egjs
latestVersion: 1.3.0
# Build settings
safe: true
markdown: kramdown
sass:
  sass_dir: _sass
exclude:
  - .gitignore
  - .grunt
  - Gruntfile.js
  - node_modules/
  - package.json
